spring:
  application:
    name: stock-service

server:
  port: 8300

eureka:
  client:
    registerWithEureka: true
    fetchRegistery: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost

